CC=clang
all: 
	$(CC) -o game_of_life -lGL -lglut game_of_life.c

of:
	$(CC) -o oscillator_finder -lcrypto oscillator_finder.c
colour:
	$(CC) -o game_of_life_colour -lGL -lglut game_of_life_colour.c	
